authentication_api:
    resource: "@ApiAuthenticationBundle/Resources/config/routing.yml"
    prefix:   /api

app_api:
    resource: "@AppApiBundle/Controller/"
    type:     annotation
    prefix:   /api

nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /blog-api/doc

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /admin
    
